;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        beginning-of-visual-line
        c-electric-colon
        c-electric-semi&comma
        c-electric-slash
        dired-copy-filename-as-kill
        dired-next-line
        dired-previous-line
        electric-newline-and-maybe-indent
        end-of-visual-line
        kill-region
        move-line-down
        move-line-up
        move-text-down
        move-text-up
        org-self-insert-command
        sp-remove-active-pair-overlay
        ))

(setq mc/cmds-to-run-once
      '(
        TeX-command-master
        TeX-command-run-all
        TeX-view
        counsel-M-x
        counsel-find-file
        dired-unmark-backward
        eval-last-sexp
        ivy-switch-buffer
        mouse-delete-window
        mouse-set-region
        pdf-util-image-map-mouse-event-proxy
        pdf-view-mouse-set-region
        python-shell-send-buffer
        spacemacs/toggle-maximize-buffer
        ))
